-- Your SQL goes here
CREATE TABLE "address" (
                           "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                           "address_line" text COLLATE "pg_catalog"."default" NOT NULL,
                           "city" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                           "postal_code" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                           "country" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                           "address_type" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                           CONSTRAINT "address_pkey" PRIMARY KEY ("id")
);
COMMENT ON COLUMN "address"."address_type" IS 'Individuals/Headquarters';

CREATE TABLE "client" (
                          "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                          "address_id" int4 NOT NULL,
                          "client_type" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                          "nif" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                          CONSTRAINT "client_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "person" (
                          "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                          "image" text,
                          "phone_number" varchar(255),
                          "role" text,
                          "address_id" int4,
                          "client_id" int4,
                          CONSTRAINT "person_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "task" (
                        "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        "client_id" int4 NOT NULL,
                        "start_time" timestamptz,
                        "end_time" timestamptz,
                        "status" text DEFAULT '',
                        "description" text NOT NULL DEFAULT '',
                        "user_id" int4,
                        "sync_with_calendar" bool,
                        "created" timestamptz NOT NULL,
                        "summary" text,
                        "location" text,
                        "calendar_uid" int4,
                        PRIMARY KEY ("id")
);

CREATE TABLE "user" (
                        "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        "person_id" int4,
                        "email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                        "hashed_password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                        CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "user_auth_token" (
                                   "user_id" int4 NOT NULL,
                                   "login_session" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                   "generated_at" timestamptz(6) NOT NULL,
                                   "expires_at" timestamptz(6) NOT NULL,
                                   CONSTRAINT "user_auth_token_pkey" PRIMARY KEY ("user_id")
);

ALTER TABLE "client" ADD CONSTRAINT "fk_client_client_1" FOREIGN KEY ("address_id") REFERENCES "address" ("id");
ALTER TABLE "person" ADD CONSTRAINT "fk_person_person_1" FOREIGN KEY ("client_id") REFERENCES "client" ("id");
ALTER TABLE "person" ADD CONSTRAINT "fk_person_person_2" FOREIGN KEY ("address_id") REFERENCES "address" ("id");
ALTER TABLE "task" ADD CONSTRAINT "fk_task_task_1" FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "task" ADD CONSTRAINT "fk_task_task_2" FOREIGN KEY ("client_id") REFERENCES "client" ("id");
ALTER TABLE "user" ADD CONSTRAINT "fk_user_user_1" FOREIGN KEY ("person_id") REFERENCES "person" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "user_auth_token" ADD CONSTRAINT "fk_user_auth_token_user_auth_token_1" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;


