-- Your SQL goes here
CREATE TABLE "task" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "client_id" int4 NOT NULL,
  "start_time" timestamptz,
  "end_time" timestamptz,
  "status" text DEFAULT '',
  "description" text DEFAULT '',
  "user_id" int4,
  PRIMARY KEY ("id")
);

ALTER TABLE "task" ADD CONSTRAINT "fk_task_task_1" FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "task" ADD CONSTRAINT "fk_task_task_2" FOREIGN KEY ("client_id") REFERENCES "client" ("id");

