DROP TABLE "client" CASCADE;

CREATE TABLE "client" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "address_id" int4 NOT NULL,
  "client_type" varchar(255) NOT NULL,
  "nif" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

